### ISSUE TITLE
Inconsistent property names?

### ISSUE THREAD

**Issue by ajbdev** [heroespatchnotes/heroes-patch-data#1]
Looks like the last few patches have been using snakecase and camelcase interchangeably on property names. I could code around this fact but I figured this was just a typo. 

I'm happy to fix this for you but wanted to confirm that this wasn't intentional and confirm the casing you want for all property names (I assume camelcase).

**Comment by stuaroo** [comment]
Wow, that's bad work on my part, sorry about that.  Yes, camelcase is what I was going for, will get that fixed.
